using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace MiniMap.SourceGenerators;

public sealed record MapModel
{
    public string Id { get; }
    public ImmutableArray<MapMethod> Methods { get; }
    public string FullNamespaceName { get; }
    public string ClassName { get; }
    public string? Pattern { get; }
    public bool AllowAnonymous { get; }
    public bool Authorize { get; }
    public bool DisableAntiforgery { get; }

    public MapModel(
        string id,
        ImmutableArray<MapMethod> methods,
        string fullNamespaceName,
        string className,
        string? pattern,
        bool allowAnonymous,
        bool authorize,
        bool disableAntiforgery
    )
    {
        Id = id;
        Methods = methods;
        FullNamespaceName = fullNamespaceName;
        ClassName = className;
        Pattern = pattern;
        AllowAnonymous = allowAnonymous;
        Authorize = authorize;
        DisableAntiforgery = disableAntiforgery;
    }

    public void Write(SourceProductionContext context)
    {
        if (Pattern is null)
        {
            throw new ArgumentNullException("pattern", "pattern must not be null");
        }

        var usings = """"
using global::Microsoft.AspNetCore.Builder;   
"""";
        if (Methods.Length > 1)
        {
            usings += "\nusing HttpMethods = global::Microsoft.AspNetCore.Http.HttpMethods;";
        }
        var configureEndpoint = string.Empty;
        if (AllowAnonymous)
        {
            configureEndpoint += "\n            .AllowAnonymous()";
        }
        if (Authorize)
        {
            configureEndpoint += "\n            .RequireAuthorization()";
        }
        if (DisableAntiforgery)
        {
            configureEndpoint += "\n            .DisableAntiforgery()";
        }

        context.AddSource(
            $"{ClassName}.g.cs",
            $$"""
// <auto-generated />
/// <summary>
/// Auto-generated Map method to register endpoint route by MiniMap.
/// </summary>

{{usings}}

namespace {{FullNamespaceName}};

public static partial class {{ClassName}}
{
    public static void Map(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)
    {
        builder.{{CallMapMethod(Pattern, Methods, $"{Id}.HandleAsync")}}{{configureEndpoint}};
    }
}

"""
        );
    }

    private static string CallMapMethod(
        string pattern,
        ImmutableArray<MapMethod> methods,
        string requestDelegate
    )
    {
        if (methods.Length > 1)
        {
            return $"MapMethods(\"{pattern}\", new global::System.Collections.Generic.List<string>() {{ {string.Join(", ", methods.Select(GetMapMethodFullyQualifiedName))} }}, {requestDelegate})";
        }

        return $"{GetMapMethodMethod(methods[0])}(\"{pattern}\", {requestDelegate})";
    }

    private static string GetMapMethodFullyQualifiedName(MapMethod method)
    {
        return method switch
        {
            MapMethod.Get => "HttpMethods.Get",
            MapMethod.Post => "HttpMethods.Post",
            MapMethod.Put => "HttpMethods.Put",
            MapMethod.Delete => "HttpMethods.Delete",
            MapMethod.Patch => "HttpMethods.Patch",
            _ => throw new InvalidOperationException(),
        };
    }

    private static string GetMapMethodMethod(MapMethod method)
    {
        return method switch
        {
            MapMethod.Get => "MapGet",
            MapMethod.Post => "MapPost",
            MapMethod.Put => "MapPut",
            MapMethod.Delete => "MapDelete",
            MapMethod.Patch => "MapPatch",
            _ => throw new InvalidOperationException(),
        };
    }
}
