using Microsoft.CodeAnalysis;

namespace MiniMap.SourceGenerators;

public sealed class MapModel(
    string id,
    MapMethod[] methods,
    string fullNamespaceName,
    string className,
    string? pattern,
    bool allowAnonymous,
    bool authorize
)
{
    public string Id { get; } = id;
    public MapMethod[] Methods { get; set; } = methods;
    public string FullNamespaceName { get; } = fullNamespaceName;
    public string ClassName { get; } = className;
    public string? Pattern { get; set; } = pattern;
    public bool AllowAnonymous { get; } = allowAnonymous;
    public bool Authorize { get; } = authorize;

    public void Write(SourceProductionContext context)
    {
        if (Pattern is null)
        {
            throw new ArgumentNullException("pattern", "pattern must not be null");
        }

        var configureEndpoint = string.Empty;
        if (AllowAnonymous)
        {
            configureEndpoint += ".AllowAnonymous()";
        }
        if (Authorize)
        {
            configureEndpoint += ".RequireAuthorization()";
        }

        context.AddSource(
            $"{ClassName}.g.cs",
            $$"""
// <auto-generated/>
// This file is auto-generated by MiniMap. DO NOT EDIT.

namespace {{FullNamespaceName}};

public static partial class {{ClassName}}
{
    public static void Map(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)
    {
        builder.{{CallMapMethod(Pattern, Methods, $"{Id}.HandleAsync")}}{{configureEndpoint}};
    }
}

"""
        );
    }

    private static string CallMapMethod(string pattern, MapMethod[] methods, string requestDelegate)
    {
        if (methods.Length > 1)
        {
            return $"MapMethods(\"{pattern}\", new List<string>() {{ {string.Join(", ", methods.Select(GetMapMethodFullyQualifiedName))} }}, {requestDelegate})";
        }

        return $"{GetMapMethodMethod(methods[0])}(\"{pattern}\", {requestDelegate})";
    }

    private static string GetMapMethodFullyQualifiedName(MapMethod method)
    {
        return method switch
        {
            MapMethod.Get => "global::Microsoft.AspNetCore.Http.HttpMethods.Get",
            MapMethod.Post => "global::Microsoft.AspNetCore.Http.HttpMethods.Post",
            MapMethod.Put => "global::Microsoft.AspNetCore.Http.HttpMethods.Put",
            MapMethod.Delete => "global::Microsoft.AspNetCore.Http.HttpMethods.Delete",
            MapMethod.Patch => "global::Microsoft.AspNetCore.Http.HttpMethods.Patch",
            _ => throw new InvalidOperationException(),
        };
    }

    private static string GetMapMethodMethod(MapMethod method)
    {
        return method switch
        {
            MapMethod.Get => "MapGet",
            MapMethod.Post => "MapPost",
            MapMethod.Put => "MapPut",
            MapMethod.Delete => "MapDelete",
            MapMethod.Patch => "MapPatch",
            _ => throw new InvalidOperationException(),
        };
    }
}
